id = "calc"
name = "Calc"
description = "Calc language support for Zed"
version = "0.0.1"
schema_version = 1
authors = []

[language_servers.calc]
name = "Calc LSP"
languages = ["Calc"]

[grammars.calc]
repository = "https://github.com/djboardman/tree-sitter-calc"
rev = "e2eaafdc71ebbafce5671cf71d5a10ba1bb15c2c"
