id = "calc"
name = "Calc"
description = "Calc language support for Zed"
version = "0.0.1"
schema_version = 1
authors = []

[language_servers.calc]
name = "Calc LSP"
languages = ["Calc"]

[grammars.calc]
repository = "https://github.com/djboardman/tree-sitter-calc"
rev = "c1fbc8eaa6da9d508337a39e71ca8e537af81a6f"
