id = "calc"
name = "Calc"
description = "Calc language support for Zed"
version = "0.0.1"
schema_version = 1
authors = []

[language_servers.calc]
name = "Calc LSP"
languages = ["Calc"]

[grammars.calc]
repository = "file:///Users/david/src/tries/2026-05-17-calc/calc/tree-sitter-calc"
rev = "da2692a647023445577b473565a6d363bf142a5e"
